### ISSUE TITLE
代码架构整理

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa/overlays#257]
这个项目看上去是我们想要的样子：
https://github.com/neggles/cm4io-fan/blob/master/dkms.post_build

**Comment by CodeChenL** [comment]
makefile也要模仿吗，还是就模仿几个dkms脚本就行了

**Comment by RadxaYuntian** [comment]
目标是我们dkms包安装了能生成dtbo并复制到`/usr/lib/linux-image-$kver/`目录里面去，同时不影响我们现有的makefile命令CLI
