### ISSUE TITLE
ROCK Pi S的I2C1 overlay是多余的

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa/overlays#269]
https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/rockchip/rk3308-rock-pi-s.dts#L208-L210
https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3308-i2c1.dts#L7

看一看这个I2C1有没有被其他设备使用，如果没有被使用则需要在bsp里面添加一个删除i2c1结点的patch

**Comment by nascs** [comment]
软件上就只是打开了，硬件上也没有什么 i2c 设备连接

**Comment by RadxaYuntian** [comment]
bsp里面给.stable-6.1和.stable-6.6添加patch把i2c默认关闭吧

**Comment by RadxaYuntian** [comment]
把开启的结点删掉就好

**Comment by nascs** [comment]
见 [bsp pr 89](https://github.com/radxa-repo/bsp/pull/89)

**Comment by RadxaYuntian** [comment]
要在PR的正文里面写`Close radxa/overlays#269`才能把issue和PR关联起来，并且在PR合并时自动关闭这个issue

**Comment by sriram-rs** [comment]
Thanks for opening this issue, @RadxaYuntian
