### ISSUE TITLE
How to comile this repo with the kernel?

### ISSUE THREAD

**Issue by yg1031** [radxa/overlays#9]
Hi, I want to make csi camera(imx219) work on Rock3A(RK3568) with android 11.
I'm new to android, please tell me how to compile this repo with the kernel.

**Comment by RadxaYuntian** [comment]
This repo is not designed to be used with Android directly. You will have to modify the Android's kernel DTS directly, as I don't think Android contains the necessary code to support DTB overlay usage.

**Comment by yg1031** [comment]
> This repo is not designed to be used with Android directly. You will have to modify the Android's kernel DTS directly, as I don't think Android contains the necessary code to support DTB overlay usage.

Thanks for your quick reply!
